"""create_movie_table

Revision ID: bc765a377768
Revises: 
Create Date: 2023-10-10 00:59:50.601783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc765a377768'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('director', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('imdb_score', sa.Float(precision=1), nullable=False),
    sa.Column('popularity', sa.Float(precision=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movies_director'), ['director'], unique=False)
        batch_op.create_index(batch_op.f('ix_movies_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movies_name'))
        batch_op.drop_index(batch_op.f('ix_movies_director'))

    op.drop_table('movies')
    # ### end Alembic commands ###
